[functions]
  directory = "functions/"

[build]
  publish = "public/"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "/webfinger/:rs"
  status = 200
  query = { resource = ":rs" }

[[redirects]]
  from = "/a/*"
  to = "https://github.com/randName/activitypub-log/commit/:splat"

[[redirects]]
  from = "/p/*"
  to = "https://github.com/randName/activitypub-log/blob/omo/posts/:splat"

[[redirects]]
  from = "/activity/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/1910"
  to = "https://www.youtube.com/playlist?list=PLWzc8EoGPqaWr6NFeRG2Pa0TCV3szEupt"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "Origin,Content-Type,Accept,Host,Date,Digest,Signature"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/actor"
  [headers.values]
    Content-Type = "application/activity+json"
