[functions]
  directory = "functions/"

[build]
  publish = "dist/"
  command = "rm -rf dist/ && cp -r public dist && npm run generate"

# CORS
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "Origin,Content-Type,Accept,Host,Date,Digest,Signature"
    Access-Control-Allow-Credentials = "true"

###############
# ActivityPub #
###############

# WebFinger
[[redirects]]
  from = "/.well-known/webfinger"
  to = "/webfinger/:rs"
  status = 200
  query = { resource = ":rs" }

[[headers]]
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/jrd+json"

# serverless endpoints
[[redirects]]
  from = "/ap/*"
  to = "/.netlify/functions/ap-:splat"
  status = 200

# static endpoints
[[headers]]
  for = "/i"
  [headers.values]
    Content-Type = "application/activity+json"
